version: '3'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      # - /usr/src/app/node_modules/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=s4ngwoo_user_dev
      - POSTGRES_PASSWORD=s4ngwoo_pw_dev
      - POSTGRES_DB=s4ngwoo_dev
volumes:
  postgres_data: